version: '3.8'

services:
  web:
    build: .
    container_name: almoxif_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./ssl:/etc/apache2/ssl
      - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./vhost-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    networks:
      - almoxif_net
    command: >
      bash -c "
      a2enmod ssl &&
      a2ensite default-ssl &&
      apache2-foreground
      "

  db:
    image: mysql:5.7
    container_name: almoxif_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: almoxif
      MYSQL_USER: almox
      MYSQL_PASSWORD: almox123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    command: --sql-mode=""
    networks:
      - almoxif_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: almoxif_pma
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    networks:
      - almoxif_net

networks:
  almoxif_net:
    driver: bridge

volumes:
  db_data: